# Generated by Django 3.1.3 on 2020-12-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
